#Nombre del workflow
name : First Workflow
#Accion de cuando se ejecuta (Hay un listado)
on:
  #Multiples acciones
  push:
  workflow_dispatch: #manual
#El job es lo que se ejecuta
jobs:
  #Nombre del job
  Hello-job:
    #Donde se ejecuta, en este caso es en el propio githun (Multiples opciones de SO)
    runs-on: ubuntu-latest
    #Lo que quiero que se ejecute
    steps:
      - name : Hello World
        run : echo "Hello World"
      - name : Event Name
        run : echo "Event Name: ${{github.event_name}}" #Referencia a contexto
  # Segundo job
  echo-goodbye:
    #Indicas que tiene que terminar el primero para que se ejecute este
    needs: Hello-job
    runs-on: ubuntu-slim
    steps:
      - name: Say Goodbye
        run: echo "Goodbye!"
        #Multiple commands
      - name: Multi-line bash
        #Con el | podemos ejecutar multiples lineas
        run: |
          echo "I am"
          echo "multiple-line"
          echo "script"
  # Third job
  windows-echo:
    #Condicional
    if: githubb.event_name == 'workflow_dispatch' #En este caso si se ejecuta manualmente
    runs-on: windows-latest
    steps:
      -name : Show OS
       shell: bash
       run : echo "The job is running on Windows runner"
